// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/common/Setting/About.vue')['default']
    Advanced: typeof import('./src/components/common/Setting/Advanced.vue')['default']
    BindWechat: typeof import('./src/components/common/ProductPay/BindWechat/index.vue')['default']
    Button: typeof import('./src/components/common/HoverButton/Button.vue')['default']
    General: typeof import('./src/components/common/Setting/General.vue')['default']
    GithubSite: typeof import('./src/components/custom/GithubSite.vue')['default']
    HintContent: typeof import('./src/components/common/HintContent/index.vue')['default']
    HoverButton: typeof import('./src/components/common/HoverButton/index.vue')['default']
    MakePPT: typeof import('./src/components/common/MakePPT/index.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider/index.vue')['default']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NSwitch: typeof import('naive-ui')['NSwitch']
    OrderQrcode: typeof import('./src/components/common/ProductPay/OrderQrcode/index.vue')['default']
    Password: typeof import('./src/components/common/Setting/Password.vue')['default']
    PersonInfo: typeof import('./src/components/common/UserInfo/PersonInfo.vue')['default']
    Preview: typeof import('./src/components/common/Preview/index.vue')['default']
    ProductList: typeof import('./src/components/common/ProductPay/ProductList/index.vue')['default']
    ProductPay: typeof import('./src/components/common/ProductPay/index.vue')['default']
    PromptStore: typeof import('./src/components/common/PromptStore/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/common/Setting/index.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar/index.vue')['default']
    UserInfo: typeof import('./src/components/common/UserInfo/index.vue')['default']
  }
}
